---
apiVersion: gateway/v2
kind: Interceptor
metadata:
  name: encrypt-customers-json
spec:
  pluginClass: io.conduktor.gateway.interceptor.EncryptPlugin
  priority: 100
  config:
    topic: customers-json-encrypted
    kmsConfig:
      keyTtlMs: 5
      vault:
        uri: http://vault:8200
        token: vault-plaintext-root-token
        version: 1
    fields:
      - fieldName: last_name
        keySecretId: vault-kms://vault:8200/transit/keys/customer
      - fieldName: email
        keySecretId: vault-kms://vault:8200/transit/keys/customer