---
apiVersion: v2
kind: Topic
metadata:
    name: orders
    cluster: aiven-kafka
    catalogVisibility: PUBLIC
    descriptionIsEditable: true
    description: This is a topic description
    sqlStorage:
        retentionTimeInSecond: 42
spec:
    partitions: 1
    replicationFactor: 3
    configs:
        cleanup.policy: delete
        retention.ms: '86400000'